name: NodeJS Tests

on: [push, pull_request]
jobs:
  test:
    name: v${{ matrix.node }} @ ubuntu-latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20]
    steps:
    - name: Checkout
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
    - name: Install NodeJS v${{ matrix.node }}
      uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # v3.5.1
      with:
        node-version: ${{ matrix.node }}
    - run: npm install
    - run: npm run build
    - run: npm test